---
config:
  theme: ''
---

mindmap
  root((RAG Assistant))
    Backend(Бекенд)
      Python
      FastAPI
      LlamaIndex
      Pydantic
      Uvicorn
      WebSockets
    Frontend(Фронтенд)
      Vue 3
      Vite
      Tailwind CSS
      PrimeVue
      Pinia
      Axios
    Cloud Services(Хмарні сервіси)
      LlamaCloud
      OpenAI GPT-4o
      OpenAI Embeddings