---
config:
  theme: 'neutral'
---

graph TB
A["Галузеві<br/>Документи"] --> B["Розбиття (Chunking)"]
B --> C1["Chunk 1"]
B --> C2["Chunk 2"]
B --> C3["Chunk 3"]
C1 --> D["Векторізація  <br/>Embedding"]
C2 --> D
C3 --> D
D --> F["Векторна База Знань"]

style A fill:#fff9c4,stroke:#f57f17,stroke-width:2px
style F fill:#c8e6c9,stroke:#388e3c,stroke-width:2px