---
config:
  theme: 'neutral'
---

flowchart LR

    subgraph Row1["Крок 1"]
        A["Запит користувача"] --> B["Векторизація"]
        B --> C["Векторний пошук"]
        C --> D["30 кандидатів"]
    end

    subgraph Row2["Крок 2"]
        E["Reranking"] --> F["10 найкращих кандидатів"]
        F --> G["Формування контексту"]
        G --> H["Генерація відповіді"]
    end

    Row1 --> Row2
